sudo: required

language: bash

services:
  - docker
  
script:
# TODO modify this line to execute the test
 - docker run --rm -it --name df-shellcheck -v $(pwd):/usr/src:ro --workdir /usr/src r.j3ss.co/shellcheck ./test.sh

matrix:
  fast_finish: true
