sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
# TODO modify this line to execute the test
 - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/test.sh

matrix:
  fast_finish: true