language: bash

services:
  - docker

script:
 - make test
 - make all

 matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
fast_finish: true
